### ISSUE TITLE
请教一下，百度地图初始化需要传入applicationContext

### ISSUE THREAD

**Issue by xfmax** [oasisfeng/condom#14]
百度地图初始化需要传入applicationContext，使用Condom封装后明显类型不匹配，有什么办法解决吗？
![qq20170904-110448](https://user-images.githubusercontent.com/11729753/30010282-3f025254-9161-11e7-9ef8-f9a8d7e3ce27.png)
![qq20170904-110510](https://user-images.githubusercontent.com/11729753/30010300-5569a5b0-9161-11e7-8beb-f6919680f92d.png)

**Comment by oasisfeng** [comment]
CondomContext.getApplicationContext().
