### ISSUE TITLE
[doc] Some map SDK may access unwrapped context with View.getContext()

### ISSUE THREAD

**Issue by haruue** [oasisfeng/condom#16]
Some map SDK requires developers put their `MapView` into layout file. For a example, amap use these demo code in their [reference][1]:

``` xml
<com.amap.api.maps.MapView
    android:id="@+id/map"
    android:layout_width="match_parent"
    android:layout_height="match_parent"/>
```

If we use these views in our layout xml, their views will be constructed in `LayoutInflater` of Activity and [use Activity itself as Context][2]. And then these SDK may access unwrapped context with `View.getContext()`. This also figures out why these map SDK just does not need a initialization method. 

To prevent this, we can construct these views in Activity.onCreate() and add their to layout manually. For a example, following Kotlin code acts same as above layout written in xml:

``` kotlin
map = MapView(CondomContext.wrap(this, "MapView")).apply {
    layoutParams = CoordinatorLayout.LayoutParams(MATCH_PARENT, MATCH_PARENT)
}
layout.addView(map, 0)
```

Replace `this` with `applicationContext` also work properly. 

Do you have any better idea?

   [1]: http://lbs.amap.com/api/android-sdk/guide/create-map/show-map "Reference of amap, see section 3 for these demonstration codes."
   [2]: http://androidxref.com/8.0.0_r4/xref/frameworks/base/core/java/android/app/Activity.java#6913 "Activity constructs PhoneWindow here with 'this', and PhoneWindow constructs LayoutInflater, which will be use in Activity."

**Comment by haruue** [comment]
A similar issue and closed 1 years ago: https://github.com/oasisfeng/condom/issues/7
But it seems that they have not find this problem. So I open a new one.

**Comment by oasisfeng** [comment]
I'd suggest overridding `onGetLayoutInflater()` in `Fragment`:
```
public void onGetLayoutInflater() {
    return super.onGetLayoutInflater.cloneIntoContext(CondomContext.wrap(...));
}
```

This could save your code from complicated changes.

**Comment by haruue** [comment]
Work well in support library >= 25.4.0

However, `Activity` does not have a similar method and it has full control over layout inflate process of `setContentView()` actually. And framewors' `Fragment.onGetLayoutInflater()` added in API level 26. Although these things are not recommended. 

Since this issue aim to provide advice for project doc and usage, I will close it now.

**Comment by oasisfeng** [comment]
@haruue For plain old activity, you can always grab a `LayoutInflater` and `cloneIntoContent()` then `inflate()` manually.

It's far simpler than creating the MapView manually.

**Comment by oasisfeng** [comment]
Thanks for your use case, I've updated README with above instructions.
