### ISSUE TITLE
Q: Greenify says this is missing from every app?

### ISSUE THREAD

**Issue by TPS** [oasisfeng/condom#19]
@oasisfeng Whenever I try `Check Convention Fulfillment` on _any_ app in Greenify (Donation, but not root), it toasts that this project is missing.  Is it supposed to be compiled into Greenify itself or the app I'm checking?  If the latter, that severely limits its usefulness.

**Comment by oasisfeng** [comment]
Sorry, "Check Convention Fulfilment" is for developer use only.

**Comment by TPS** [comment]
Then probably wiser to hide behind some debug/&c setting, no?

**Comment by rocket14** [comment]
Same here. Dumb to have it available in the app for everybody when it should be hidden for developers only to access
