### ISSUE TITLE
为什么用 GPL。。。

### ISSUE THREAD

**Issue by aviraxp** [oasisfeng/condom#2]
大大限制了适用范围

**Comment by oasisfeng** [comment]
这是一个误会。这个项目的License其实是GPL的一个分支，全称是GPL v2 with Java Class-path Exception。因为工程中使用了OpenJDK的类源码，约束了此工程的License。

这个License的约束力上类似于LGPL，而非标准的GPL，可以在闭源及商业app中使用。只是对工程的代码修改需要延续同样的License开源。

参见：http://softwareengineering.stackexchange.com/questions/119436

**Comment by liudongmiao** [comment]
应该可以申明，你的部分是啥协议，期中隐含了别人的又是啥协议吧…

此外，都叫 condom 了，不如用 fuck 协议：WTFPL

**Comment by oasisfeng** [comment]
之前遇到的GPL问题已经排除，为避免更多误会，已正式修改为Apache License Version 2.0。
