### ISSUE TITLE
Will this project work with Android P?

### ISSUE THREAD

**Issue by LanderlYoung** [oasisfeng/condom#21]
As I just noticed, this project uses "android stub" to access @hide APIs.
Clearly, those APIs are private, and in Android P any call to those APIs should be blocked.

So, my question is will the project work with android P?

**Comment by oasisfeng** [comment]
So far so good. I'll continue to inspect the compatibility with Android P as it marches to final release.

**Comment by oasisfeng** [comment]
Full support for Android 9 in v2.3.1.
