### ISSUE TITLE
Hook sd-card access?

### ISSUE THREAD

**Issue by LanderlYoung** [oasisfeng/condom#22]
Since those APIs are not in Context but Environment class, some SDK requires WRITE_EXTERNAL_STORAGE permission and write casually in it, which is quite annoying.

Current consideration: use AOP technology to hook class level method calls to Environment class.
Drawback: ill-behaved SDK may hardcode sd card path...(However IOException must be cached, the app won't crash, but sdk may not function normally.)

**Comment by oasisfeng** [comment]
Any viable AOP solution suggested? The bottom line is not making Project Condom hard to integrate or increasing the risk of incompatibility.
