### ISSUE TITLE
为什么不增加 Activity 的拦截？

### ISSUE THREAD

**Issue by plokmju88** [oasisfeng/condom#23]
我看到四大组件里，除了 Activity 都有了，这是为什么呢？
我想会不会是因为，Activity 的打开是可见的，所以没有必要拦截。
但是我遇到一个问题，有一些 SDK 的 Service，会在后台默默的开启 Activity，然后关闭掉，我想对这部分做监听和拦截，但是 CondomContext 无法被继承，因为构造方法中存在 CondomCore。

**Comment by oasisfeng** [comment]
原因的确如你所述。请问能否给出所提到在后台默默启动 Activity 的 SDK？我会在研究后给出下一步的计划。

PS, CondomContext 设计为不能被继承，是沿袭了 ContextWrapper 的组合而非继承的设计思想。所以，你可以使用 ContextWrapper 轻松扩展 CondomContext 的能力。
