### ISSUE TITLE
getSystemService的拦截问题

### ISSUE THREAD

**Issue by 3c** [oasisfeng/condom#25]
通过CondomContext包装的condomContext， getSystemService 会被拦截到。
但如果
``` condomContext.startSerivce(new Intent(condomContext,DemoService.class));```

DemoService 里面的getSystemService就无法拦截到了

这个有无解决方案？

**Comment by oasisfeng** [comment]
CondomProcess 正是针对上述问题的。如果你的 app 集成了 SDK 中的组件，请加上 CondomProcess。

**Comment by 3c** [comment]
CondomProcess只限于单独的进程， 如果service是在主进程运行的，则没有效果

另外即便是单独的进程service，只能阻止链式启动，无法拦截getSystemService

**Comment by oasisfeng** [comment]
CondomProcess 目前还没有支持拦截 CondomKit（拦截 getSystemService）。

能否详述一下具体的使用场景，最好能具体到特定的 SDK 和问题，以便考虑提供合适的解决方案。

**Comment by oasisfeng** [comment]
因久无下文，关闭此问题。如有新的信息补充，请继续回复。
