### ISSUE TITLE
Warning: com.oasisfeng.condom.CondomContentResolver: can't find referenced class android.content.IContentProvider

### ISSUE THREAD

**Issue by PixxelSong** [oasisfeng/condom#26]
gradle进来这个之后，我却无法打包app了
![image](https://user-images.githubusercontent.com/25476054/50222390-13ff6c00-03d3-11e9-9ee5-821f813a33be.png)

看起来是混淆出了问题
![image](https://user-images.githubusercontent.com/25476054/50222224-95a2ca00-03d2-11e9-8c26-4074ea49fce5.png)

同时爆出了三个warning
![image](https://user-images.githubusercontent.com/25476054/50222262-b834e300-03d2-11e9-8748-5995b9ec36d8.png)
![image](https://user-images.githubusercontent.com/25476054/50222279-c71b9580-03d2-11e9-955c-b500cd4ead27.png)
![image](https://user-images.githubusercontent.com/25476054/50222301-d4d11b00-03d2-11e9-95d3-8681b69aa646.png)

**Comment by oasisfeng** [comment]
Fixed in v2.3.1
