### ISSUE TITLE
碰上坏坏的淫们怎么办？

### ISSUE THREAD

**Issue by lirenlong** [oasisfeng/condom#3]
坏坏的淫们如果反射拿：

1. ActivityThread::currentApplication
2. AppGlobals::getInitialApplication

我们是不是只能怀了....

就像坏坏的淫们在tt上扎了几个孔。

@oasisfeng

**Comment by ifynn** [comment]
这工程描述也是没谁了

**Comment by liudongmiao** [comment]
其实根本用不着反射，他就在那，只需要假装他在那就好…弄个 hidden-api 就好。

但是，其实吧，application 的 context 和 其他的 context 还是有差别的…我同样担心这个 Safe Context 的影响。

还是觉得，使用第三方插件的人，未必不知道会恶意唤醒，未必不想被恶意唤醒。而是否恶意，谁又能说得清呢？调支付宝支付是善意，调微信分享是善意，调百度来给推广就不是了么？

**Comment by lirenlong** [comment]
所以@oasisfeng 大牛设计了一个白名单询问机制，由使用者按需设置: 不在白里的压根不能唤起其组件，在白里的，也不能后台唤起或stopped package的唤起。

**Comment by oasisfeng** [comment]
@liudongmiao 这只是一个开源的library，被三方SDK强奸的开发者希望用它保护一下自身和名誉，自会用它；原本就打算与强奸者同流合污的开发团队，想必也不屑于戴套。就这么简单。

@lirenlong 一个小小的套套自然防不住想要千方百计洞穿它的坏人。就我观察到的大部分国内SDK的代码水平，还真不敢对他们寄予这么高的期望。不过话说回来，如果真的有这一天出现了，说明Project Condom在国内Android开发界中的影响力也足够大了，这时候做SDK的团队恐怕已经不敢一意孤行的跟自己的客户对着干了。

**Comment by oasisfeng** [comment]
@liudongmiao CondomContext 所提供的 getApplicationContext() 背后就是原始 context 的 application context。你担心的影响，可否详述？

**Comment by ChinaZeng** [comment]
为何这么屌
