### ISSUE TITLE
像极光推送，还是没法拦截

### ISSUE THREAD

**Issue by Lemniscate317** [oasisfeng/condom#33]
我接入了极光的推送和分享，每个init都是传的condomContext，也设置了CondomProcess.installExceptDefaultProcess(this)，还设置了option，都没能禁止调唤醒第三方，我是通过miui设置中的应用行为记录中看到的，我看到自己的app还是去唤醒了别人的app，只是被禁止了。然后我在option的allow回调中，没有看到唤醒别家的包名，所以我就有点奇怪纳闷

**Comment by Lemniscate317** [comment]
可以install在当前的进程中，然后自己判断，我看到回调有我想要的包名了，尝试屏蔽ing

**Comment by LollipopKit** [comment]
想问问怎么做的
如下给jpush套了ComdomContext：
```java
JPushInterface.init(CondomContext.wrap(context, "JPush")); 
```

如下继承了Application：
```java
package x.xx.xxx;

import com.oasisfeng.condom.CondomProcess;
import android.app.Application;

public class MyApplication extends Application {
    @Override public void onCreate() {
      CondomProcess.installExceptDefaultProcess(this);
    }
}
```
请教下哪里做的不对？不是很懂Android原生开发，谢谢了

**Comment by Lemniscate317** [comment]
> 想问问怎么做的
> 如下给jpush套了ComdomContext：
> 
> ```java
> JPushInterface.init(CondomContext.wrap(context, "JPush")); 
> ```
> 
> 如下继承了Application：
> 
> ```java
> package x.xx.xxx;
> 
> import com.oasisfeng.condom.CondomProcess;
> import android.app.Application;
> 
> public class MyApplication extends Application {
>     @Override public void onCreate() {
>       CondomProcess.installExceptDefaultProcess(this);
>     }
> }
> ```
> 
> 请教下哪里做的不对？不是很懂Android原生开发，谢谢了

他还有一个installcurrprocess。然后还可以传一个config，你在这个config里面可以打印他的startservice，会发现固定的几个值，然后这几个return false

**Comment by LollipopKit** [comment]
用了installCurrentProcess，option全部返回false，也没法拦截。。。不管了，换mipush
