### ISSUE TITLE
可否release打包好的jar或aar？

### ISSUE THREAD

**Issue by aviraxp** [oasisfeng/condom#4]
或者上传到maven，这样在gradle配置一下就行了

**Comment by oasisfeng** [comment]
正在准备中，谢谢关注！

**Comment by Qixingchen** [comment]
可以使用 https://jitpack.io/#oasisfeng/condom
这样可以最大化减少所需的操作

**Comment by oasisfeng** [comment]
还有一两项小的改善，完成之后将会release一个版本。

**Comment by oasisfeng** [comment]
1.0.0 已发布到 jcenter 仓库。

**Comment by aviraxp** [comment]
编译 release 版本的话，我这里需要两条 proguard 规则

-dontwarn android.content.ContentResolver
-dontwarn javax.annotation.**

**Comment by oasisfeng** [comment]
@aviraxp 这确是目前aar打包的一个小瑕疵，尚未找到合适的build.gradle语法用于移除其中的两个桩class，不过对运行期的功能没有影响。我再研究一下如何移除桩class。

**Comment by drakeet** [comment]
@oasisfeng 可以使用 consumerProguardFiles 内置这两 dontwarn.

**Comment by oasisfeng** [comment]
我release了1.0.1，已经移除了stub class。请尝试：

```compile 'com.oasisfeng.condom:library:1.0.1'```

**Comment by aviraxp** [comment]
Warning:com.oasisfeng.condom.CondomContext$CondomContentResolver: can't find referenced class android.content.IContentProvider
Warning:com.oasisfeng.condom.ContentResolverWrapper: can't find referenced method 'android.content.IContentProvider acquireProvider(android.content.Context,java.lang.String)' in library class android.content.ContentResolver
Warning:com.oasisfeng.condom.ContentResolverWrapper: can't find referenced method 'android.content.IContentProvider acquireExistingProvider(android.content.Context,java.lang.String)' in library class android.content.ContentResolver
Warning:com.oasisfeng.condom.ContentResolverWrapper: can't find referenced method 'boolean releaseProvider(android.content.IContentProvider)' in library class android.content.ContentResolver
Warning:com.oasisfeng.condom.ContentResolverWrapper: can't find referenced method 'android.content.IContentProvider acquireUnstableProvider(android.content.Context,java.lang.String)' in library class android.content.ContentResolver
Warning:com.oasisfeng.condom.ContentResolverWrapper: can't find referenced method 'boolean releaseUnstableProvider(android.content.IContentProvider)' in library class android.content.ContentResolver
Warning:com.oasisfeng.condom.ContentResolverWrapper: can't find referenced method 'void unstableProviderDied(android.content.IContentProvider)' in library class android.content.ContentResolver
Warning:com.oasisfeng.condom.ContentResolverWrapper: can't find referenced class android.content.IContentProvider
Warning:there were 11 unresolved references to classes or interfaces.
Warning:there were 6 unresolved references to library class members.
Warning:Exception while processing task java.io.IOException: Please correct the above warnings first.
Error:Execution failed for task ':app:transformClassesAndResourcesWithProguardForRelease'.
> Job failed, see logs for details

**Comment by oasisfeng** [comment]
看来ProGuard配置还是不可或缺…… 我先添加上 @drakeet 指出的 consumerProguardFiles。

**Comment by oasisfeng** [comment]
包含ProGuard配置的1.0.2已发布。
