### ISSUE TITLE
ProGuard 配置

### ISSUE THREAD

**Issue by magicboylinw** [oasisfeng/condom#6]
有些 sdk 通过反射调用方法，例如 微博 sdk，得加上 ProGuard 的配置：
`-keep class com.oasisfeng.condom.** { *; }`
或者
`-keep class com.oasisfeng.condom.CondomContext { *; }`

**Comment by oasisfeng** [comment]
如果使用的是Gradle build，需要确保android build插件的版本是1.3以上，就可以自动获得对应的ProGuard规则。
如果不是用gradle构建，那么需要手动在项目的ProGuard规则中添加以下规则：
https://github.com/oasisfeng/condom/blob/master/library/proguard-rules.pro

**Comment by oasisfeng** [comment]
另外，1.1.1版本修复了一个1.1.0版本中ProGuard规则缺失导致的运行期可能出现的AbstractMethodError。
