### ISSUE TITLE
面对百度、高德地图这样的SDK该如何处理？

### ISSUE THREAD

**Issue by HarborZeng** [oasisfeng/condom#7]
此类地图并未在Application里面拿到context

**Comment by oasisfeng** [comment]
可否详细解释一下这类SDK的调用模式？其Context的获取途径是？
CondomProcess机制是否能解决这个case？

**Comment by HarborZeng** [comment]
我不知道自己怎么看您的文档的，真是犯傻了，唯独没看到这一段，哈哈。用CondomProcess解决了呢，它的原理就是一个remote的service
