### ISSUE TITLE
Bugly报错java.lang.AbstractMethodError

### ISSUE THREAD

**Issue by Kuanghusing** [oasisfeng/condom#9]
bugly的应用升级sdk，一点更新就报错
java.lang.AbstractMethodError
abstract method "android.graphics.drawable.Drawable android.content.pm.PackageManager.getUserBadgeForDensity(android.os.UserHandle, int)"
com.tencent.bugly.beta.ui.c.void a(com.tencent.bugly.beta.download.DownloadTask)(BUGLY:103)

**Comment by oasisfeng** [comment]
请问运行的Android版本是？

**Comment by Kuanghusing** [comment]
暂时发现5.0-6.0都有这个问题

**Comment by oasisfeng** [comment]
这个问题是由于上述SDK使用了PackageManager的内部隐藏API导致的，我会在近日修复。

**Comment by kkseay** [comment]
同上问题，但是追溯过去是极光推送的。
abstract method "android.graphics.drawable.Drawable android.content.pm.PackageManager.getUserBadgeForDensity(android.os.UserHandle, int)"
出错堆栈
1	android.app.Notification$Builder.getProfileBadgeDrawable(Notification.java:2928)
2	android.app.Notification$Builder.hasThreeLines(Notification.java:3173)
3	android.app.Notification$Builder.build(Notification.java:3742)
4	cn.jpush.android.api.DefaultPushNotificationBuilder.a(Unknown Source)
5	cn.jpush.android.api.DefaultPushNotificationBuilder.a(Unknown Source)
6	cn.jpush.android.api.n.b(Unknown Source)
7	cn.jpush.android.api.n.a(Unknown Source)
8	cn.jpush.android.data.n.run(Unknown Source)

**Comment by oasisfeng** [comment]
Fixed in commit 8c88b4fbe76255768c81c475811405fa93ebb97e

**Comment by oasisfeng** [comment]
@Kuanghusing @kkseay 请问上述问题在最新的1.2.0版本中是否已不再出现？

**Comment by kkseay** [comment]
ok了。谢谢

**Comment by peerless2012** [comment]
你好 我当前版本是1.2.0 后台报了不少这个异常

**Comment by oasisfeng** [comment]
请升级到 2.0.0 版本，已解决此问题。

**Comment by linuxhsj** [comment]
可以分享下你是怎么解决的吗

**Comment by oasisfeng** [comment]
@linuxhsj 太久远，已经不记得了。你可以试着翻下 commit log。

**Comment by chenhx37** [comment]
condom版本2.3.1，Android 8、10仍出现此问题：
    java.lang.AbstractMethodError: abstract method "android.content.IContentProvider android.content.ContentResolver.acquireProvider(android.content.Context, java.lang.String)"
        at android.content.ContentResolver.acquireProvider(ContentResolver.java:1804)
        at android.provider.Settings$ContentProviderHolder.getProvider(Settings.java:1787)
        at android.provider.Settings$NameValueCache.getStringForUser(Settings.java:1953)
        at android.provider.Settings$Secure.getStringForUser(Settings.java:4925)
        at android.provider.Settings$Secure.getString(Settings.java:4882)
